### ISSUE TITLE
"How to Use" no longer correct

### ISSUE THREAD

**Issue by matthewsymonds** [stefanRitter/flux-rails-assets#3]
2.0 changes the dispatcher from FluxDispatcher to Flux.Dispatcher.

The repo readme should be updated to reflect this change.

**Comment by craigs** [comment]
PR #2 should resolve this one for you. Make comments on the pull request if you think we can improve the documentation in any way apart from the syntax change. Happy to have a go at it.

**Comment by stefanRitter** [comment]
Thanks!
